### ISSUE TITLE
Mobile viewing difficult

### ISSUE THREAD

**Issue by Alsomjon** [Bwc9876/CodeReview#372]
**Is your feature request related to a problem? Please describe.**
When using the app in mobile, the review page where you select point values is hard to use.

**Describe the solution you'd like**
Any way to make it more concise, and clear what you're viewing. A suggestion I have would be to make a dropdown appear when you click on the category

**Comment by Bwc9876** [comment]
The website was designed for desktops as that is all students should have during class. If you have to use it on mobile just select see desktop view on your browser.
